# Generated by Django 4.0.3 on 2022-03-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sday', models.DateTimeField()),
                ('stime', models.CharField(max_length=4)),
                ('fday', models.DateTimeField()),
                ('ftime', models.CharField(max_length=4)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
