# Generated by Django 4.0.3 on 2022-03-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_fday_appointment_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.IntegerField(default=1),
        ),
    ]
