# Generated by Django 4.0.3 on 2022-03-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_appointment_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='room',
        ),
    ]
